name = "BurpenFarten"
author = "StepanKo101"
prefix = "BF"
mainprefix = "z"

[version]
major = 0
minor = 1
patch = 0
build = 0

[hemtt.launch.default]

mission = "bftest.Stratis"

parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]

executable = "arma3_x64"
file_patching = true
binarize = false
rapify = true

[hemtt.launch.cba]

extends = "default"

workshop = [
    "450814997", # CBA_A3's Workshop ID
]

[hemtt.launch.ace]

estends = "cba"

workshop = [
    "463939057", # ACE3's Workshop ID
]